name: Upload ShipCore Framework to Steam Workshop

permissions:
  contents: read

concurrency:
  group: steam-workshop-upload
  cancel-in-progress: false

on:
  push:
    branches:
      - main
    paths:
      - ShipCoreFramework/**
  workflow_dispatch:
    inputs:
      sbmi_profile:
        description: "Metadata profile file to use"
        required: true
        default: main
        type: choice
        options:
          - main
          - beta

jobs:
  upload:
    uses: ./.github/workflows/steam-workshop-upload.yml
    with:
      mod_dir: ShipCoreFramework
      src_dir: ShipCoreFramework/src
      workshop_dir: ShipCoreFramework/workshop
      sbmi_profile: ${{ github.event_name == 'workflow_dispatch' && inputs.sbmi_profile || 'beta' }}
    secrets: inherit
